# Generated by Django 5.2.3 on 2025-06-29 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_addded', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(upload_to='chai_images')),
                ('type', models.CharField(choices=[('gr', 'Green Tea'), ('bl', 'Black Tea'), ('mi', 'Milk Tea'), ('he', 'Herbal Tea')], max_length=2)),
            ],
        ),
    ]
