# Generated by Django 5.2.3 on 2025-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chai',
            old_name='date_addded',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='chai',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
