# Generated by Django 5.2.3 on 2025-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chai', '0002_rename_date_addded_chai_date_added_chai_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
