# Generated by Django 5.2.3 on 2025-07-04 17:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chai', '0004_chai_short_description_chai_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chai_review',
            old_name='review_text',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='chai_review',
            name='chai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Chai.chai'),
        ),
        migrations.CreateModel(
            name='Chai_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField()),
                ('chai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='Chai.chai')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(default='', max_length=200)),
                ('chai', models.ManyToManyField(related_name='stores', to='Chai.chai')),
            ],
        ),
    ]
